//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id_order { get; set; }
        public Nullable<int> Order_number { get; set; }
        public string Article { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> Order_date { get; set; }
        public Nullable<System.DateTime> Delivery_date { get; set; }
        public Nullable<int> Id_address { get; set; }
        public Nullable<int> Id_user { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> Id_status { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Tovar Tovar { get; set; }
        public virtual User User { get; set; }
    }
}
