//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.Order = new HashSet<Order>();
        }
    
        public string Article { get; set; }
        public Nullable<int> Type { get; set; }
        public string Measurement { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Id_supplier { get; set; }
        public Nullable<int> Id_manufacturer { get; set; }
        public Nullable<int> Id_category { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Manufactureres Manufactureres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Supplieres Supplieres { get; set; }
        public virtual Types Types { get; set; }
    }
}
